function [conv2d_18, state] = vesselFcn(input, params, varargin)
%VESSELFCN Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 13
%
% Variable names in this function are taken from the original ONNX file.
%
% [CONV2D_18] = vesselFcn(INPUT, PARAMS)
%			- Evaluates the imported ONNX network VESSELFCN with input(s)
%			INPUT and the imported network parameters in PARAMS. Returns
%			network output(s) in CONV2D_18.
%
% [CONV2D_18, STATE] = vesselFcn(INPUT, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = vesselFcn(INPUT, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% INPUT
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  INPUT:		[unk__438, 256, 256, 3]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% CONV2D_18
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  CONV2D_18:		[unk__439, 256, 256, 1]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[input, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(input, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'input'}, {input}, [4]);
% Call the top-level graph function:
[conv2d_18, conv2d_18NumDims, state] = tf2onnxGraph1000(input, NumDims.input, Vars, NumDims, Training, params.State);
% Postprocess the output data
[conv2d_18] = postprocessOutput(conv2d_18, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [conv2d_18, conv2d_18NumDims1088, state] = tf2onnxGraph1000(input, inputNumDims1087, Vars, NumDims, Training, state)
% Function implementing the graph 'tf2onnxGraph1000'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.input = input;
NumDims.input = inputNumDims1087;

% Execute the operators:
% Transpose:
[perm, NumDims.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd__1] = prepareTransposeArgs(Vars.TransposePerm1001, NumDims.input);
if isempty(perm)
    Vars.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd__1 = Vars.input;
else
    Vars.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd__1 = permute(Vars.input, perm);
end

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd_0] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_1_convolutio, Vars.DRIVE_Vessel_U_Net_1_conv2d_1_Squeeze_0, Vars.ConvStride1002, Vars.ConvDilationFactor1003,Vars.ConvPadding1004, 1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd__1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_1_convolutio);
Vars.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd_0 = dlconv(Vars.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd__1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_4 = Vars.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd_0 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_2;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_4 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_1_BiasAdd_0, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_2);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_1 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_4 + Vars.const_fold_opt__421;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_1 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_4, NumDims.const_fold_opt__421);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_1_Relu_0 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_1));
NumDims.DRIVE_Vessel_U_Net_1_activation_1_Relu_0 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_1;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_1_2_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_1_2_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_1_2_Squeeze_, Vars.ConvStride1005, Vars.ConvDilationFactor1006,Vars.ConvPadding1007, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_1_Relu_0, NumDims.DRIVE_Vessel_U_Net_1_conv2d_1_2_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_1_2_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_1_Relu_0, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_49 = Vars.DRIVE_Vessel_U_Net_1_conv2d_1_2_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_47;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_49 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_1_2_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_47);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_46 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_49 + Vars.const_fold_opt__423;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_46 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_49, NumDims.const_fold_opt__423);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_1_2_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_46));
NumDims.DRIVE_Vessel_U_Net_1_activation_1_2_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_46;

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_max_pooling2d_1_M_1] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1008, Vars.MaxPoolStride1009, Vars.MaxPoolPadding1010, NumDims.DRIVE_Vessel_U_Net_1_activation_1_2_Re_1);
Vars.DRIVE_Vessel_U_Net_1_max_pooling2d_1_M_1 = maxpool(Vars.DRIVE_Vessel_U_Net_1_activation_1_2_Re_1, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_2_1_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_2_1_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_2_1_Squeeze_, Vars.ConvStride1011, Vars.ConvDilationFactor1012,Vars.ConvPadding1013, 1, NumDims.DRIVE_Vessel_U_Net_1_max_pooling2d_1_M_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_2_1_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_2_1_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_max_pooling2d_1_M_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_54 = Vars.DRIVE_Vessel_U_Net_1_conv2d_2_1_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_52;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_54 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_2_1_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_52);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_51 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_54 + Vars.const_fold_opt__430;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_51 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_54, NumDims.const_fold_opt__430);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_2_1_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_51));
NumDims.DRIVE_Vessel_U_Net_1_activation_2_1_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_51;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_3_1_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_3_1_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_3_1_Squeeze_, Vars.ConvStride1014, Vars.ConvDilationFactor1015,Vars.ConvPadding1016, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_2_1_Re_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_3_1_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_3_1_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_2_1_Re_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_59 = Vars.DRIVE_Vessel_U_Net_1_conv2d_3_1_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_57;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_59 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_3_1_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_57);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_56 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_59 + Vars.const_fold_opt__431;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_56 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_59, NumDims.const_fold_opt__431);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_3_1_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_56));
NumDims.DRIVE_Vessel_U_Net_1_activation_3_1_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_56;

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_max_pooling2d_1_2_1] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1017, Vars.MaxPoolStride1018, Vars.MaxPoolPadding1019, NumDims.DRIVE_Vessel_U_Net_1_activation_3_1_Re_1);
Vars.DRIVE_Vessel_U_Net_1_max_pooling2d_1_2_1 = maxpool(Vars.DRIVE_Vessel_U_Net_1_activation_3_1_Re_1, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_4_1_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_4_1_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_4_1_Squeeze_, Vars.ConvStride1020, Vars.ConvDilationFactor1021,Vars.ConvPadding1022, 1, NumDims.DRIVE_Vessel_U_Net_1_max_pooling2d_1_2_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_4_1_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_4_1_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_max_pooling2d_1_2_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_64 = Vars.DRIVE_Vessel_U_Net_1_conv2d_4_1_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_62;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_64 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_4_1_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_62);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_61 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_64 + Vars.const_fold_opt__432;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_61 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_64, NumDims.const_fold_opt__432);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_4_1_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_61));
NumDims.DRIVE_Vessel_U_Net_1_activation_4_1_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_61;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_5_1_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_5_1_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_5_1_Squeeze_, Vars.ConvStride1023, Vars.ConvDilationFactor1024,Vars.ConvPadding1025, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_4_1_Re_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_5_1_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_5_1_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_4_1_Re_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_69 = Vars.DRIVE_Vessel_U_Net_1_conv2d_5_1_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_67;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_69 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_5_1_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_67);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_66 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_69 + Vars.const_fold_opt__434;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_66 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_69, NumDims.const_fold_opt__434);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_5_1_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_66));
NumDims.DRIVE_Vessel_U_Net_1_activation_5_1_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_66;

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_max_pooling2d_2_1_1] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1026, Vars.MaxPoolStride1027, Vars.MaxPoolPadding1028, NumDims.DRIVE_Vessel_U_Net_1_activation_5_1_Re_1);
Vars.DRIVE_Vessel_U_Net_1_max_pooling2d_2_1_1 = maxpool(Vars.DRIVE_Vessel_U_Net_1_activation_5_1_Re_1, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_6_1_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_6_1_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_6_1_Squeeze_, Vars.ConvStride1029, Vars.ConvDilationFactor1030,Vars.ConvPadding1031, 1, NumDims.DRIVE_Vessel_U_Net_1_max_pooling2d_2_1_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_6_1_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_6_1_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_max_pooling2d_2_1_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_74 = Vars.DRIVE_Vessel_U_Net_1_conv2d_6_1_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_72;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_74 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_6_1_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_72);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_71 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_74 + Vars.const_fold_opt__417;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_71 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_74, NumDims.const_fold_opt__417);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_6_1_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_71));
NumDims.DRIVE_Vessel_U_Net_1_activation_6_1_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_71;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_7_1_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_7_1_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_7_1_Squeeze_, Vars.ConvStride1032, Vars.ConvDilationFactor1033,Vars.ConvPadding1034, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_6_1_Re_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_7_1_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_7_1_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_6_1_Re_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_79 = Vars.DRIVE_Vessel_U_Net_1_conv2d_7_1_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_77;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_79 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_7_1_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_77);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_76 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_79 + Vars.const_fold_opt__433;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_76 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_79, NumDims.const_fold_opt__433);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_7_1_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_76));
NumDims.DRIVE_Vessel_U_Net_1_activation_7_1_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_76;

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_max_pooling2d_3_1_1] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1035, Vars.MaxPoolStride1036, Vars.MaxPoolPadding1037, NumDims.DRIVE_Vessel_U_Net_1_activation_7_1_Re_1);
Vars.DRIVE_Vessel_U_Net_1_max_pooling2d_3_1_1 = maxpool(Vars.DRIVE_Vessel_U_Net_1_activation_7_1_Re_1, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_8_1_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_8_1_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_8_1_Squeeze_, Vars.ConvStride1038, Vars.ConvDilationFactor1039,Vars.ConvPadding1040, 1, NumDims.DRIVE_Vessel_U_Net_1_max_pooling2d_3_1_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_8_1_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_8_1_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_max_pooling2d_3_1_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_84 = Vars.DRIVE_Vessel_U_Net_1_conv2d_8_1_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_82;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_84 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_8_1_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_82);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_81 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_84 + Vars.const_fold_opt__437;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_81 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_84, NumDims.const_fold_opt__437);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_8_1_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_81));
NumDims.DRIVE_Vessel_U_Net_1_activation_8_1_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_81;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_9_1_BiasAdd_] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_9_1_convolut, Vars.DRIVE_Vessel_U_Net_1_conv2d_9_1_Squeeze_, Vars.ConvStride1041, Vars.ConvDilationFactor1042,Vars.ConvPadding1043, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_8_1_Re_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_9_1_convolut);
Vars.DRIVE_Vessel_U_Net_1_conv2d_9_1_BiasAdd_ = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_8_1_Re_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_89 = Vars.DRIVE_Vessel_U_Net_1_conv2d_9_1_BiasAdd_ .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_87;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_89 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_9_1_BiasAdd_, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_87);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_86 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_89 + Vars.const_fold_opt__435;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_86 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_89, NumDims.const_fold_opt__435);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_9_1_Re_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_86));
NumDims.DRIVE_Vessel_U_Net_1_activation_9_1_Re_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_86;

% ConvTranspose:
[weights, bias, stride, dilation, cropping, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose__1] = prepareConvTransposeArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__3, Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__2, Vars.ConvTransposeStride1044, Vars.ConvTransposeDilationFactor1045, Vars.ConvTransposePads1046, "NOTSET", Vars.ConvTransposeOutputShape1047, 1, size(Vars.DRIVE_Vessel_U_Net_1_activation_9_1_Re_1), NumDims.DRIVE_Vessel_U_Net_1_activation_9_1_Re_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose__3);
Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__1 = dltranspconv(Vars.DRIVE_Vessel_U_Net_1_activation_9_1_Re_1, weights, bias, 'Stride', stride, 'DilationFactor', dilation, 'Cropping', cropping, 'DataFormat', dataFormat);

% Concat:
[Vars.DRIVE_Vessel_U_Net_1_concatenate_1_con_1, NumDims.DRIVE_Vessel_U_Net_1_concatenate_1_con_1] = onnxConcat(1, {Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__1, Vars.DRIVE_Vessel_U_Net_1_activation_7_1_Re_1}, [NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose__1, NumDims.DRIVE_Vessel_U_Net_1_activation_7_1_Re_1]);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_10_1_BiasA_1] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_10_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_10_1_Squeeze, Vars.ConvStride1048, Vars.ConvDilationFactor1049,Vars.ConvPadding1050, 1, NumDims.DRIVE_Vessel_U_Net_1_concatenate_1_con_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_10_1_convolu);
Vars.DRIVE_Vessel_U_Net_1_conv2d_10_1_BiasA_1 = dlconv(Vars.DRIVE_Vessel_U_Net_1_concatenate_1_con_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_9 = Vars.DRIVE_Vessel_U_Net_1_conv2d_10_1_BiasA_1 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_7;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_9 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_10_1_BiasA_1, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_7);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_6 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_9 + Vars.const_fold_opt__415;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_6 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_9, NumDims.const_fold_opt__415);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_10_1_R_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizati_6));
NumDims.DRIVE_Vessel_U_Net_1_activation_10_1_R_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizati_6;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_11_1_BiasA_1] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_11_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_11_1_Squeeze, Vars.ConvStride1051, Vars.ConvDilationFactor1052,Vars.ConvPadding1053, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_10_1_R_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_11_1_convolu);
Vars.DRIVE_Vessel_U_Net_1_conv2d_11_1_BiasA_1 = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_10_1_R_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_14 = Vars.DRIVE_Vessel_U_Net_1_conv2d_11_1_BiasA_1 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_12;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_14 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_11_1_BiasA_1, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_12);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_11 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_14 + Vars.const_fold_opt__419;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_11 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_14, NumDims.const_fold_opt__419);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_11_1_R_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_11));
NumDims.DRIVE_Vessel_U_Net_1_activation_11_1_R_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_11;

% ConvTranspose:
[weights, bias, stride, dilation, cropping, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose__5] = prepareConvTransposeArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__7, Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__6, Vars.ConvTransposeStride1054, Vars.ConvTransposeDilationFactor1055, Vars.ConvTransposePads1056, "NOTSET", Vars.ConvTransposeOutputShape1057, 1, size(Vars.DRIVE_Vessel_U_Net_1_activation_11_1_R_1), NumDims.DRIVE_Vessel_U_Net_1_activation_11_1_R_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose__7);
Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__5 = dltranspconv(Vars.DRIVE_Vessel_U_Net_1_activation_11_1_R_1, weights, bias, 'Stride', stride, 'DilationFactor', dilation, 'Cropping', cropping, 'DataFormat', dataFormat);

% Concat:
[Vars.DRIVE_Vessel_U_Net_1_concatenate_1_2_c_1, NumDims.DRIVE_Vessel_U_Net_1_concatenate_1_2_c_1] = onnxConcat(1, {Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__5, Vars.DRIVE_Vessel_U_Net_1_activation_5_1_Re_1}, [NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose__5, NumDims.DRIVE_Vessel_U_Net_1_activation_5_1_Re_1]);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_12_1_BiasA_1] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_12_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_12_1_Squeeze, Vars.ConvStride1058, Vars.ConvDilationFactor1059,Vars.ConvPadding1060, 1, NumDims.DRIVE_Vessel_U_Net_1_concatenate_1_2_c_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_12_1_convolu);
Vars.DRIVE_Vessel_U_Net_1_conv2d_12_1_BiasA_1 = dlconv(Vars.DRIVE_Vessel_U_Net_1_concatenate_1_2_c_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_19 = Vars.DRIVE_Vessel_U_Net_1_conv2d_12_1_BiasA_1 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_17;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_19 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_12_1_BiasA_1, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_17);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_16 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_19 + Vars.const_fold_opt__429;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_16 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_19, NumDims.const_fold_opt__429);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_12_1_R_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_16));
NumDims.DRIVE_Vessel_U_Net_1_activation_12_1_R_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_16;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_13_1_BiasA_1] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_13_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_13_1_Squeeze, Vars.ConvStride1061, Vars.ConvDilationFactor1062,Vars.ConvPadding1063, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_12_1_R_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_13_1_convolu);
Vars.DRIVE_Vessel_U_Net_1_conv2d_13_1_BiasA_1 = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_12_1_R_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_24 = Vars.DRIVE_Vessel_U_Net_1_conv2d_13_1_BiasA_1 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_22;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_24 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_13_1_BiasA_1, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_22);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_21 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_24 + Vars.const_fold_opt__426;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_21 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_24, NumDims.const_fold_opt__426);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_13_1_R_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_21));
NumDims.DRIVE_Vessel_U_Net_1_activation_13_1_R_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_21;

% ConvTranspose:
[weights, bias, stride, dilation, cropping, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose__8] = prepareConvTransposeArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose_10, Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__9, Vars.ConvTransposeStride1064, Vars.ConvTransposeDilationFactor1065, Vars.ConvTransposePads1066, "NOTSET", Vars.ConvTransposeOutputShape1067, 1, size(Vars.DRIVE_Vessel_U_Net_1_activation_13_1_R_1), NumDims.DRIVE_Vessel_U_Net_1_activation_13_1_R_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose_10);
Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__8 = dltranspconv(Vars.DRIVE_Vessel_U_Net_1_activation_13_1_R_1, weights, bias, 'Stride', stride, 'DilationFactor', dilation, 'Cropping', cropping, 'DataFormat', dataFormat);

% Concat:
[Vars.DRIVE_Vessel_U_Net_1_concatenate_2_1_c_1, NumDims.DRIVE_Vessel_U_Net_1_concatenate_2_1_c_1] = onnxConcat(1, {Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose__8, Vars.DRIVE_Vessel_U_Net_1_activation_3_1_Re_1}, [NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose__8, NumDims.DRIVE_Vessel_U_Net_1_activation_3_1_Re_1]);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_14_1_BiasA_1] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_14_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_14_1_Squeeze, Vars.ConvStride1068, Vars.ConvDilationFactor1069,Vars.ConvPadding1070, 1, NumDims.DRIVE_Vessel_U_Net_1_concatenate_2_1_c_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_14_1_convolu);
Vars.DRIVE_Vessel_U_Net_1_conv2d_14_1_BiasA_1 = dlconv(Vars.DRIVE_Vessel_U_Net_1_concatenate_2_1_c_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_29 = Vars.DRIVE_Vessel_U_Net_1_conv2d_14_1_BiasA_1 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_27;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_29 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_14_1_BiasA_1, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_27);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_26 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_29 + Vars.const_fold_opt__422;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_26 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_29, NumDims.const_fold_opt__422);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_14_1_R_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_26));
NumDims.DRIVE_Vessel_U_Net_1_activation_14_1_R_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_26;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_15_1_BiasA_1] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_15_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_15_1_Squeeze, Vars.ConvStride1071, Vars.ConvDilationFactor1072,Vars.ConvPadding1073, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_14_1_R_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_15_1_convolu);
Vars.DRIVE_Vessel_U_Net_1_conv2d_15_1_BiasA_1 = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_14_1_R_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_34 = Vars.DRIVE_Vessel_U_Net_1_conv2d_15_1_BiasA_1 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_32;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_34 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_15_1_BiasA_1, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_32);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_31 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_34 + Vars.const_fold_opt__427;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_31 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_34, NumDims.const_fold_opt__427);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_15_1_R_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_31));
NumDims.DRIVE_Vessel_U_Net_1_activation_15_1_R_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_31;

% ConvTranspose:
[weights, bias, stride, dilation, cropping, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose_11] = prepareConvTransposeArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose_13, Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose_12, Vars.ConvTransposeStride1074, Vars.ConvTransposeDilationFactor1075, Vars.ConvTransposePads1076, "NOTSET", Vars.ConvTransposeOutputShape1077, 1, size(Vars.DRIVE_Vessel_U_Net_1_activation_15_1_R_1), NumDims.DRIVE_Vessel_U_Net_1_activation_15_1_R_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose_13);
Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose_11 = dltranspconv(Vars.DRIVE_Vessel_U_Net_1_activation_15_1_R_1, weights, bias, 'Stride', stride, 'DilationFactor', dilation, 'Cropping', cropping, 'DataFormat', dataFormat);

% Concat:
[Vars.DRIVE_Vessel_U_Net_1_concatenate_3_1_c_1, NumDims.DRIVE_Vessel_U_Net_1_concatenate_3_1_c_1] = onnxConcat(1, {Vars.DRIVE_Vessel_U_Net_1_conv2d_transpose_11, Vars.DRIVE_Vessel_U_Net_1_activation_1_2_Re_1}, [NumDims.DRIVE_Vessel_U_Net_1_conv2d_transpose_11, NumDims.DRIVE_Vessel_U_Net_1_activation_1_2_Re_1]);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_16_1_BiasA_1] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_16_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_16_1_Squeeze, Vars.ConvStride1078, Vars.ConvDilationFactor1079,Vars.ConvPadding1080, 1, NumDims.DRIVE_Vessel_U_Net_1_concatenate_3_1_c_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_16_1_convolu);
Vars.DRIVE_Vessel_U_Net_1_conv2d_16_1_BiasA_1 = dlconv(Vars.DRIVE_Vessel_U_Net_1_concatenate_3_1_c_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_39 = Vars.DRIVE_Vessel_U_Net_1_conv2d_16_1_BiasA_1 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_37;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_39 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_16_1_BiasA_1, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_37);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_36 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_39 + Vars.const_fold_opt__428;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_36 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_39, NumDims.const_fold_opt__428);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_16_1_R_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_36));
NumDims.DRIVE_Vessel_U_Net_1_activation_16_1_R_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_36;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.DRIVE_Vessel_U_Net_1_conv2d_17_1_BiasA_1] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_17_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_17_1_Squeeze, Vars.ConvStride1081, Vars.ConvDilationFactor1082,Vars.ConvPadding1083, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_16_1_R_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_17_1_convolu);
Vars.DRIVE_Vessel_U_Net_1_conv2d_17_1_BiasA_1 = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_16_1_R_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Mul:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_44 = Vars.DRIVE_Vessel_U_Net_1_conv2d_17_1_BiasA_1 .* Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_42;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_44 = max(NumDims.DRIVE_Vessel_U_Net_1_conv2d_17_1_BiasA_1, NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_42);

% Add:
Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_41 = Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_44 + Vars.const_fold_opt__425;
NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_41 = max(NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_44, NumDims.const_fold_opt__425);

% Relu:
Vars.DRIVE_Vessel_U_Net_1_activation_17_1_R_1 = relu(dlarray(Vars.DRIVE_Vessel_U_Net_1_batch_normalizat_41));
NumDims.DRIVE_Vessel_U_Net_1_activation_17_1_R_1 = NumDims.DRIVE_Vessel_U_Net_1_batch_normalizat_41;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.Conv__334_0] = prepareConvArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_18_1_convolu, Vars.DRIVE_Vessel_U_Net_1_conv2d_18_1_Reshape, Vars.ConvStride1084, Vars.ConvDilationFactor1085,Vars.ConvPadding1086, 1, NumDims.DRIVE_Vessel_U_Net_1_activation_17_1_R_1, NumDims.DRIVE_Vessel_U_Net_1_conv2d_18_1_convolu);
Vars.Conv__334_0 = dlconv(Vars.DRIVE_Vessel_U_Net_1_activation_17_1_R_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Sigmoid:
Vars.DRIVE_Vessel_U_Net_1_conv2d_18_1_Sigmo_1 = sigmoid(dlarray(Vars.Conv__334_0));
NumDims.DRIVE_Vessel_U_Net_1_conv2d_18_1_Sigmo_1 = NumDims.Conv__334_0;

% Reshape:
[shape, NumDims.conv2d_18] = prepareReshapeArgs(Vars.DRIVE_Vessel_U_Net_1_conv2d_18_1_Sigmo_1, Vars.new_shape__392, NumDims.DRIVE_Vessel_U_Net_1_conv2d_18_1_Sigmo_1, 0);
Vars.conv2d_18 = reshape(Vars.DRIVE_Vessel_U_Net_1_conv2d_18_1_Sigmo_1, shape{:});

% Set graph output arguments from Vars and NumDims:
conv2d_18 = Vars.conv2d_18;
conv2d_18NumDims1088 = NumDims.conv2d_18;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(input, numDataOutputs, params, varargin)
% Function to validate inputs to vesselFcn:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'input', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, input, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,1);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [input, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(input, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(input, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {input}));
% Make the input variables into unlabelled dlarrays:
input = makeUnlabeledDlarray(input);
% Permute inputs if requested:
input = permuteInputVar(input, inputDataPerms{1}, 4);
% Check input size(s):
checkInputSize(size(input), {'unk__438' 256 256 3}, "input");
end

function [conv2d_18] = postprocessOutput(conv2d_18, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(conv2d_18)
        conv2d_18 = extractdata(conv2d_18);
    end
end
% Permute outputs if requested:
conv2d_18 = permuteOutputVar(conv2d_18, outputDataPerms{1}, 4);
end


%% dlarray functions implementing ONNX operators:

function [Y, numDimsY] = onnxConcat(ONNXAxis, XCell, numDimsXArray)
% Concatentation that treats all empties the same. Necessary because
% dlarray.cat does not allow, for example, cat(1, 1x1, 1x0) because the
% second dimension sizes do not match.

% Copyright 2021 The MathWorks, Inc.

numDimsY = numDimsXArray(1);
XCell(cellfun(@isempty, XCell)) = [];
if isempty(XCell)
    Y = dlarray([]);
else
    if ONNXAxis<0
        ONNXAxis = ONNXAxis + numDimsY;
    end
    DLTAxis = numDimsY - ONNXAxis;
    Y = cat(DLTAxis, XCell{:});
end
end

function [weights, bias, stride, dilationFactor, padding, dataFormat, numDimsY] = prepareConvArgs(...
    weights, bias, stride, dilationFactor, padding, numWtGroups, numDimsX, numDimsW)
% Prepares arguments for implementing the ONNX Conv operator

%   Copyright 2020 The MathWorks, Inc.

% Weights: The ONNX weight dim is Fcxyz..., where c=C/G, G is numGroups,
% and xyz... are spatial dimensions. DLT "weights" here is the flip of
% that, or ...zyxcF. dlconv requires ...zyxcfG, where f=F/G. So reshape to
% split the last dimension.
sizeW    = size(weights, 1:numDimsW);
F        = sizeW(end);
newWSize = [sizeW(1:numDimsW-1), F/numWtGroups, numWtGroups];
weights  = reshape(weights, newWSize);
% bias
if isempty(bias)
    bias = 0;
end
bias = dlarray(bias(:),'CU');
% Derive missing default attributes from weight tensor
numSpatialDims = numDimsW-2;
if isempty(padding)
    padding = zeros(1, 2*numSpatialDims);
end
if isempty(stride)
    stride = ones(1,numSpatialDims);
end
if isempty(dilationFactor)
    dilationFactor = ones(1,numSpatialDims);
end
% Make the attributes non-dlarrays:
if isa(stride, 'dlarray')
    stride = extractdata(stride);
end
if isa(dilationFactor, 'dlarray')
    dilationFactor = extractdata(dilationFactor);
end
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
% Make the attributes double row vectors, and flip their dimension ordering
% to reverse-onnx:
stride = fliplr(double(stride(:)'));
dilationFactor = fliplr(double(dilationFactor(:)'));
if isnumeric(padding)       % padding can be "same"
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
% Set dataformat and numdims
dataFormat = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY = numDimsX;
end

function [weights, bias, stride, dilation, cropping, dataFormat, numDimsY] = prepareConvTransposeArgs(ONNXWeights, bias, stride, dilation, pads, auto_pad, output_shape, numWtGroups, sizeX, numDimsX, numDimsW)
% Prepares arguments for implementing the ONNX ConvTranspose operator

%   Copyright 2020-2021 The MathWorks, Inc.

% The ONNX weight dim is Cfhwd..., where f=F/G, G is numGroups and hwd...
% are the spatial dimensions of the kernel. The input argumnt "ONNXWeights"
% here is the flip of that, or ...dwhfC. We want ...dwhfcG, where c=C/G. So
% we just need to perform a reshape to split the last dimension from C to
% cG.
sizeW       = size(ONNXWeights, 1:numDimsW);
C           = sizeW(end);
newWSize    = [sizeW(1:numDimsW-1), C/numWtGroups, numWtGroups];
weights     = reshape(ONNXWeights, newWSize);
if isempty(bias)
    bias = 0;
end
bias = dlarray(bias(:),'CU');
% Derive missing default attributes from weight tensor
numSpatialDims = numDimsW-2;
if isempty(pads)
    pads = zeros(1, 2*numSpatialDims);
end
if isempty(stride)
    stride = ones(1,numSpatialDims);
end
if isempty(dilation)
    dilation = ones(1,numSpatialDims);
end
% Make the attributes non-dlarrays:
if isa(stride, 'dlarray')
    stride = extractdata(stride);
end
if isa(dilation, 'dlarray')
    dilation = extractdata(dilation);
end
if isa(pads, 'dlarray')
    pads = extractdata(pads);
end
if isa(output_shape, 'dlarray')
    output_shape = extractdata(output_shape);
end
if ~isempty(output_shape)
    % Process output_shape. The ONNX Doc says:
    % "If output_shape is specified pads values are ignored."
    % And then 'pads' is recalculated as follows:
    % total_padding[i] = stride[i] * (input_size[i] - 1) + output_padding[i] + ((kernel_shape[i] - 1) * dilations[i] + 1) - output_shape[i]
    % If (auto_pads == SAME_UPPER): pads[start_i] = total_padding[i]/2; pads[end_i] = total_padding[i] - (total_padding[i]/2)
    % Else: pads[start_i] = total_padding[i] - (total_padding[i]/2); pads[end_i] = (total_padding[i]/2).

    % sizeX is reverse-onnx with trailing singletons dropped. ...zyxCN.
    % Extract the ONNX spatial shape as 'input_size', and put it in forward
    % ONNX ordering.
    if numDimsX > numel(sizeX)
        sizeX = [sizeX, ones(1,numDimsX-numel(sizeX))];     % sizeX is now ...zyxCN
    end
    input_size = fliplr(sizeX(1:numSpatialDims));     % xyz...
    % Recover the kernel_shape from the weights in forward ONNX ordering
    kernel_shape = fliplr(sizeW(1:numSpatialDims));
    % Calculate the new pads value in forward ONNX ordering
    output_padding = 0;             % output_padding is not supported (yet).
    D = numel(input_size);
    for i = 1:D
        total_padding(i) = stride(i) * (input_size(i) - 1) + output_padding + ((kernel_shape(i) - 1) * dilation(i) + 1) - output_shape(i);
        start_i = i;
        end_i = D+i;
        if auto_pad=="SAME_UPPER"
            pads(start_i) = floor(total_padding(i)/2);
            pads(end_i) = total_padding(i) - floor(total_padding(i)/2);
        else
            pads(start_i) = total_padding(i) - floor(total_padding(i)/2);
            pads(end_i) = floor(total_padding(i)/2);
        end
    end
end
% Make the attributes double row vectors, and flip their dimension ordering
% to reverse-onnx:
stride = fliplr(double(stride(:)'));
dilation = fliplr(double(dilation(:)'));
if isnumeric(pads)       % padding can be "same"
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the left-right flip and the semicolon)
    pads = fliplr(transpose(reshape(pads, [], 2)));
end
cropping = pads;
dataFormat  = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY = numDimsX;
end

function [poolsize, stride, padding, dataFormat, numDimsY, numDimsIndices] = prepareMaxPool8Args(poolsize, stride, padding, numDimsX)
% Prepares arguments for implementing the ONNX MaxPool-8 operator

%   Copyright 2020 The MathWorks, Inc.

poolsize    = fliplr(extractdata(poolsize(:)'));
stride      = fliplr(extractdata(stride(:)'));
% padding
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
if isnumeric(padding)
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
dataFormat  = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY    = numDimsX;
numDimsIndices = numDimsX;                      % New in opset 8
end

function [DLTShape, numDimsY] = prepareReshapeArgs(X, ONNXShape, numDimsX, allowzero)
% Prepares arguments for implementing the ONNX Reshape operator

%   Copyright 2020-2024 The MathWorks, Inc.

ONNXShape = flip(extractdata(ONNXShape));            % First flip the shape to make it correspond to the dimensions of X.
% In ONNX, 0 means "unchanged" if allowzero is false, and -1 means "infer". In DLT, there is no
% "unchanged", and [] means "infer".
DLTShape = num2cell(ONNXShape);                      % Make a cell array so we can include [].
% Replace zeros with the actual size if allowzero is false
if any(ONNXShape==0) && allowzero==0
    i0 = find(ONNXShape==0);
    DLTShape(i0) = num2cell(size(X, numDimsX - numel(ONNXShape) + i0));  % right-align the shape vector and dims
end
if any(ONNXShape == -1)
    % Replace -1 with []
    i = ONNXShape == -1;
    DLTShape{i} = [];
end
if numel(DLTShape)==1
    DLTShape = [DLTShape 1];
end
numDimsY = numel(ONNXShape);
end

function [perm, numDimsA] = prepareTransposeArgs(ONNXPerm, numDimsA)
% Prepares arguments for implementing the ONNX Transpose operator

%   Copyright 2020 The MathWorks, Inc.

if numDimsA <= 1        % Tensors of numDims 0 or 1 are unchanged by ONNX Transpose.
    perm = [];
else
    if isempty(ONNXPerm)        % Empty ONNXPerm means reverse the dimensions.
        perm = numDimsA:-1:1;
    else
        perm = numDimsA-flip(ONNXPerm);
    end
end
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.

%   Copyright 2020 The MathWorks, Inc.

if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

%   Copyright 2020-2021 The MathWorks, Inc.

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more

    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);

    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end

    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);

    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));

    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;

    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray

%   Copyright 2020-2021 The MathWorks, Inc.

if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)

%   Copyright 2020 The MathWorks, Inc.

% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in
% t.
%   Copyright 2020 The MathWorks, Inc.

for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
