function [output, state] = idridLesionFcn(input, params, varargin)
%IDRIDLESIONFCN Function implementing an imported ONNX network.
%
% THIS FILE WAS AUTO-GENERATED BY importONNXFunction.
% ONNX Operator Set Version: 17
%
% Variable names in this function are taken from the original ONNX file.
%
% [OUTPUT] = idridLesionFcn(INPUT, PARAMS)
%			- Evaluates the imported ONNX network IDRIDLESIONFCN with input(s)
%			INPUT and the imported network parameters in PARAMS. Returns
%			network output(s) in OUTPUT.
%
% [OUTPUT, STATE] = idridLesionFcn(INPUT, PARAMS)
%			- Additionally returns state variables in STATE. When training,
%			use this form and set TRAINING to true.
%
% [__] = idridLesionFcn(INPUT, PARAMS, 'NAME1', VAL1, 'NAME2', VAL2, ...)
%			- Specifies additional name-value pairs described below:
%
% 'Training'
% 			Boolean indicating whether the network is being evaluated for
%			prediction or training. If TRAINING is true, state variables
%			will be updated.
%
% 'InputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			 between the dimensions of the input data and the dimensions of
%			the ONNX model input. For example, the permutation from HWCN
%			(MATLAB standard) to NCHW (ONNX standard) uses the vector
%			[4 3 1 2]. See the documentation for IMPORTONNXFUNCTION for
%			more information about automatic permutation.
%
%			'none' - Input(s) are passed in the ONNX model format. See 'Inputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between input data dimensions and the expected
%			ONNX input dimensions.%
%			cell array - If the network has multiple inputs, each cell
%			contains 'auto', 'none', or a numeric vector.
%
% 'OutputDataPermutation'
%			'auto' - Automatically attempt to determine the permutation
%			between the dimensions of the output and a conventional MATLAB
%			dimension ordering. For example, the permutation from NC (ONNX
%			standard) to CN (MATLAB standard) uses the vector [2 1]. See
%			the documentation for IMPORTONNXFUNCTION for more information
%			about automatic permutation.
%
%			'none' - Return output(s) as given by the ONNX model. See 'Outputs'.
%
%			numeric vector - The permutation vector describing the
%			transformation between the ONNX output dimensions and the
%			desired output dimensions.%
%			cell array - If the network has multiple outputs, each cell
%			contains 'auto', 'none' or a numeric vector.
%
% Inputs:
% -------
% INPUT
%			- Input(s) to the ONNX network.
%			  The input size(s) expected by the ONNX file are:
%				  INPUT:		[batch, 3, 512, 768]				Type: FLOAT
%			  By default, the function will try to permute the input(s)
%			  into this dimension ordering. If the default is incorrect,
%			  use the 'InputDataPermutation' argument to control the
%			  permutation.
%
%
% PARAMS	- Network parameters returned by 'importONNXFunction'.
%
%
% Outputs:
% --------
% OUTPUT
%			- Output(s) of the ONNX network.
%			  Without permutation, the size(s) of the outputs are:
%				  OUTPUT:		[batch, 3, 512, 768]				Type: FLOAT
%			  By default, the function will try to permute the output(s)
%			  from this dimension ordering into a conventional MATLAB
%			  ordering. If the default is incorrect, use the
%			  'OutputDataPermutation' argument to control the permutation.
%
% STATE		- (Optional) State variables. When TRAINING is true, these will
% 			  have been updated from the original values in PARAMS.State.
%
%
%  See also importONNXFunction

% Preprocess the input data and arguments:
[input, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(input, params, varargin{:});
% Put all variables into a single struct to implement dynamic scoping:
[Vars, NumDims] = packageVariables(params, {'input'}, {input}, [4]);
% Call the top-level graph function:
[output, outputNumDims, state] = main_graphGraph1002(input, NumDims.input, Vars, NumDims, Training, params.State);
% Postprocess the output data
[output] = postprocessOutput(output, outputDataPerms, anyDlarrayInputs, Training, varargin{:});
end

function [output, outputNumDims1089, state] = main_graphGraph1002(input, inputNumDims1088, Vars, NumDims, Training, state)
% Function implementing the graph 'main_graphGraph1002'
% Update Vars and NumDims from the graph's formal input parameters. Note that state variables are already in Vars.
Vars.input = input;
NumDims.input = inputNumDims1088;

% Execute the operators:
% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem] = prepareConvArgs(Vars.enc1_block_0_weight, Vars.enc1_block_0_weight_bias, Vars.ConvStride1003, Vars.ConvDilationFactor1004,Vars.ConvPadding1005, 1, NumDims.input, NumDims.enc1_block_0_weight);
Vars.getitem = dlconv(Vars.input, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu1001 = relu(dlarray(Vars.getitem));
NumDims.relu1001 = NumDims.getitem;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_3] = prepareConvArgs(Vars.enc1_block_3_weight, Vars.enc1_block_3_weight_bias, Vars.ConvStride1006, Vars.ConvDilationFactor1007,Vars.ConvPadding1008, 1, NumDims.relu1001, NumDims.enc1_block_3_weight);
Vars.getitem_3 = dlconv(Vars.relu1001, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_1 = relu(dlarray(Vars.getitem_3));
NumDims.relu_1 = NumDims.getitem_3;

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.max_pool2d] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1009, Vars.MaxPoolStride1010, Vars.MaxPoolPadding1011, NumDims.relu_1);
Vars.max_pool2d = maxpool(Vars.relu_1, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_6] = prepareConvArgs(Vars.enc2_block_0_weight, Vars.enc2_block_0_weight_bias, Vars.ConvStride1012, Vars.ConvDilationFactor1013,Vars.ConvPadding1014, 1, NumDims.max_pool2d, NumDims.enc2_block_0_weight);
Vars.getitem_6 = dlconv(Vars.max_pool2d, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_2 = relu(dlarray(Vars.getitem_6));
NumDims.relu_2 = NumDims.getitem_6;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_9] = prepareConvArgs(Vars.enc2_block_3_weight, Vars.enc2_block_3_weight_bias, Vars.ConvStride1015, Vars.ConvDilationFactor1016,Vars.ConvPadding1017, 1, NumDims.relu_2, NumDims.enc2_block_3_weight);
Vars.getitem_9 = dlconv(Vars.relu_2, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_3 = relu(dlarray(Vars.getitem_9));
NumDims.relu_3 = NumDims.getitem_9;

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.max_pool2d_1] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1018, Vars.MaxPoolStride1019, Vars.MaxPoolPadding1020, NumDims.relu_3);
Vars.max_pool2d_1 = maxpool(Vars.relu_3, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_12] = prepareConvArgs(Vars.enc3_block_0_weight, Vars.enc3_block_0_weight_bias, Vars.ConvStride1021, Vars.ConvDilationFactor1022,Vars.ConvPadding1023, 1, NumDims.max_pool2d_1, NumDims.enc3_block_0_weight);
Vars.getitem_12 = dlconv(Vars.max_pool2d_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_4 = relu(dlarray(Vars.getitem_12));
NumDims.relu_4 = NumDims.getitem_12;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_15] = prepareConvArgs(Vars.enc3_block_3_weight, Vars.enc3_block_3_weight_bias, Vars.ConvStride1024, Vars.ConvDilationFactor1025,Vars.ConvPadding1026, 1, NumDims.relu_4, NumDims.enc3_block_3_weight);
Vars.getitem_15 = dlconv(Vars.relu_4, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_5 = relu(dlarray(Vars.getitem_15));
NumDims.relu_5 = NumDims.getitem_15;

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.max_pool2d_2] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1027, Vars.MaxPoolStride1028, Vars.MaxPoolPadding1029, NumDims.relu_5);
Vars.max_pool2d_2 = maxpool(Vars.relu_5, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_18] = prepareConvArgs(Vars.enc4_block_0_weight, Vars.enc4_block_0_weight_bias, Vars.ConvStride1030, Vars.ConvDilationFactor1031,Vars.ConvPadding1032, 1, NumDims.max_pool2d_2, NumDims.enc4_block_0_weight);
Vars.getitem_18 = dlconv(Vars.max_pool2d_2, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_6 = relu(dlarray(Vars.getitem_18));
NumDims.relu_6 = NumDims.getitem_18;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_21] = prepareConvArgs(Vars.enc4_block_3_weight, Vars.enc4_block_3_weight_bias, Vars.ConvStride1033, Vars.ConvDilationFactor1034,Vars.ConvPadding1035, 1, NumDims.relu_6, NumDims.enc4_block_3_weight);
Vars.getitem_21 = dlconv(Vars.relu_6, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_7 = relu(dlarray(Vars.getitem_21));
NumDims.relu_7 = NumDims.getitem_21;

% MaxPool:
[poolsize, stride, padding, dataFormat, NumDims.max_pool2d_3] = prepareMaxPool8Args(Vars.MaxPoolPoolSize1036, Vars.MaxPoolStride1037, Vars.MaxPoolPadding1038, NumDims.relu_7);
Vars.max_pool2d_3 = maxpool(Vars.relu_7, poolsize, 'Stride', stride, 'Padding', padding, 'DataFormat', dataFormat);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_24] = prepareConvArgs(Vars.bottleneck_block_0_weight, Vars.bottleneck_block_0_weight_bias, Vars.ConvStride1039, Vars.ConvDilationFactor1040,Vars.ConvPadding1041, 1, NumDims.max_pool2d_3, NumDims.bottleneck_block_0_weight);
Vars.getitem_24 = dlconv(Vars.max_pool2d_3, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_8 = relu(dlarray(Vars.getitem_24));
NumDims.relu_8 = NumDims.getitem_24;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_27] = prepareConvArgs(Vars.bottleneck_block_3_weight, Vars.bottleneck_block_3_weight_bias, Vars.ConvStride1042, Vars.ConvDilationFactor1043,Vars.ConvPadding1044, 1, NumDims.relu_8, NumDims.bottleneck_block_3_weight);
Vars.getitem_27 = dlconv(Vars.relu_8, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_9 = relu(dlarray(Vars.getitem_27));
NumDims.relu_9 = NumDims.getitem_27;

% ConvTranspose:
[weights, bias, stride, dilation, cropping, dataFormat, NumDims.convolution] = prepareConvTransposeArgs(Vars.up4_weight, Vars.up4_bias, Vars.ConvTransposeStride1045, Vars.ConvTransposeDilationFactor1046, Vars.ConvTransposePads1047, "NOTSET", Vars.ConvTransposeOutputShape1048, 1, size(Vars.relu_9), NumDims.relu_9, NumDims.up4_weight);
Vars.convolution = dltranspconv(Vars.relu_9, weights, bias, 'Stride', stride, 'DilationFactor', dilation, 'Cropping', cropping, 'DataFormat', dataFormat);

% Concat:
[Vars.cat1000, NumDims.cat1000] = onnxConcat(1, {Vars.convolution, Vars.relu_7}, [NumDims.convolution, NumDims.relu_7]);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_30] = prepareConvArgs(Vars.dec4_block_0_weight, Vars.dec4_block_0_weight_bias, Vars.ConvStride1049, Vars.ConvDilationFactor1050,Vars.ConvPadding1051, 1, NumDims.cat1000, NumDims.dec4_block_0_weight);
Vars.getitem_30 = dlconv(Vars.cat1000, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_10 = relu(dlarray(Vars.getitem_30));
NumDims.relu_10 = NumDims.getitem_30;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_33] = prepareConvArgs(Vars.dec4_block_3_weight, Vars.dec4_block_3_weight_bias, Vars.ConvStride1052, Vars.ConvDilationFactor1053,Vars.ConvPadding1054, 1, NumDims.relu_10, NumDims.dec4_block_3_weight);
Vars.getitem_33 = dlconv(Vars.relu_10, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_11 = relu(dlarray(Vars.getitem_33));
NumDims.relu_11 = NumDims.getitem_33;

% ConvTranspose:
[weights, bias, stride, dilation, cropping, dataFormat, NumDims.convolution_1] = prepareConvTransposeArgs(Vars.up3_weight, Vars.up3_bias, Vars.ConvTransposeStride1055, Vars.ConvTransposeDilationFactor1056, Vars.ConvTransposePads1057, "NOTSET", Vars.ConvTransposeOutputShape1058, 1, size(Vars.relu_11), NumDims.relu_11, NumDims.up3_weight);
Vars.convolution_1 = dltranspconv(Vars.relu_11, weights, bias, 'Stride', stride, 'DilationFactor', dilation, 'Cropping', cropping, 'DataFormat', dataFormat);

% Concat:
[Vars.cat_1, NumDims.cat_1] = onnxConcat(1, {Vars.convolution_1, Vars.relu_5}, [NumDims.convolution_1, NumDims.relu_5]);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_36] = prepareConvArgs(Vars.dec3_block_0_weight, Vars.dec3_block_0_weight_bias, Vars.ConvStride1059, Vars.ConvDilationFactor1060,Vars.ConvPadding1061, 1, NumDims.cat_1, NumDims.dec3_block_0_weight);
Vars.getitem_36 = dlconv(Vars.cat_1, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_12 = relu(dlarray(Vars.getitem_36));
NumDims.relu_12 = NumDims.getitem_36;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_39] = prepareConvArgs(Vars.dec3_block_3_weight, Vars.dec3_block_3_weight_bias, Vars.ConvStride1062, Vars.ConvDilationFactor1063,Vars.ConvPadding1064, 1, NumDims.relu_12, NumDims.dec3_block_3_weight);
Vars.getitem_39 = dlconv(Vars.relu_12, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_13 = relu(dlarray(Vars.getitem_39));
NumDims.relu_13 = NumDims.getitem_39;

% ConvTranspose:
[weights, bias, stride, dilation, cropping, dataFormat, NumDims.convolution_2] = prepareConvTransposeArgs(Vars.up2_weight, Vars.up2_bias, Vars.ConvTransposeStride1065, Vars.ConvTransposeDilationFactor1066, Vars.ConvTransposePads1067, "NOTSET", Vars.ConvTransposeOutputShape1068, 1, size(Vars.relu_13), NumDims.relu_13, NumDims.up2_weight);
Vars.convolution_2 = dltranspconv(Vars.relu_13, weights, bias, 'Stride', stride, 'DilationFactor', dilation, 'Cropping', cropping, 'DataFormat', dataFormat);

% Concat:
[Vars.cat_2, NumDims.cat_2] = onnxConcat(1, {Vars.convolution_2, Vars.relu_3}, [NumDims.convolution_2, NumDims.relu_3]);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_42] = prepareConvArgs(Vars.dec2_block_0_weight, Vars.dec2_block_0_weight_bias, Vars.ConvStride1069, Vars.ConvDilationFactor1070,Vars.ConvPadding1071, 1, NumDims.cat_2, NumDims.dec2_block_0_weight);
Vars.getitem_42 = dlconv(Vars.cat_2, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_14 = relu(dlarray(Vars.getitem_42));
NumDims.relu_14 = NumDims.getitem_42;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_45] = prepareConvArgs(Vars.dec2_block_3_weight, Vars.dec2_block_3_weight_bias, Vars.ConvStride1072, Vars.ConvDilationFactor1073,Vars.ConvPadding1074, 1, NumDims.relu_14, NumDims.dec2_block_3_weight);
Vars.getitem_45 = dlconv(Vars.relu_14, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_15 = relu(dlarray(Vars.getitem_45));
NumDims.relu_15 = NumDims.getitem_45;

% ConvTranspose:
[weights, bias, stride, dilation, cropping, dataFormat, NumDims.convolution_3] = prepareConvTransposeArgs(Vars.up1_weight, Vars.up1_bias, Vars.ConvTransposeStride1075, Vars.ConvTransposeDilationFactor1076, Vars.ConvTransposePads1077, "NOTSET", Vars.ConvTransposeOutputShape1078, 1, size(Vars.relu_15), NumDims.relu_15, NumDims.up1_weight);
Vars.convolution_3 = dltranspconv(Vars.relu_15, weights, bias, 'Stride', stride, 'DilationFactor', dilation, 'Cropping', cropping, 'DataFormat', dataFormat);

% Concat:
[Vars.cat_3, NumDims.cat_3] = onnxConcat(1, {Vars.convolution_3, Vars.relu_1}, [NumDims.convolution_3, NumDims.relu_1]);

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_48] = prepareConvArgs(Vars.dec1_block_0_weight, Vars.dec1_block_0_weight_bias, Vars.ConvStride1079, Vars.ConvDilationFactor1080,Vars.ConvPadding1081, 1, NumDims.cat_3, NumDims.dec1_block_0_weight);
Vars.getitem_48 = dlconv(Vars.cat_3, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_16 = relu(dlarray(Vars.getitem_48));
NumDims.relu_16 = NumDims.getitem_48;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.getitem_51] = prepareConvArgs(Vars.dec1_block_3_weight, Vars.dec1_block_3_weight_bias, Vars.ConvStride1082, Vars.ConvDilationFactor1083,Vars.ConvPadding1084, 1, NumDims.relu_16, NumDims.dec1_block_3_weight);
Vars.getitem_51 = dlconv(Vars.relu_16, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Relu:
Vars.relu_17 = relu(dlarray(Vars.getitem_51));
NumDims.relu_17 = NumDims.getitem_51;

% Conv:
[weights, bias, stride, dilationFactor, padding, dataFormat, NumDims.output] = prepareConvArgs(Vars.final_weight, Vars.final_bias, Vars.ConvStride1085, Vars.ConvDilationFactor1086,Vars.ConvPadding1087, 1, NumDims.relu_17, NumDims.final_weight);
Vars.output = dlconv(Vars.relu_17, weights, bias, 'Stride', stride, 'DilationFactor', dilationFactor, 'Padding', padding, 'DataFormat', dataFormat);

% Set graph output arguments from Vars and NumDims:
output = Vars.output;
outputNumDims1089 = NumDims.output;
% Set output state from Vars:
state = updateStruct(state, Vars);
end

function [inputDataPerms, outputDataPerms, Training] = parseInputs(input, numDataOutputs, params, varargin)
% Function to validate inputs to idridLesionFcn:
p = inputParser;
isValidArrayInput = @(x)isnumeric(x) || isstring(x);
isValidONNXParameters = @(x)isa(x, 'ONNXParameters');
addRequired(p, 'input', isValidArrayInput);
addRequired(p, 'params', isValidONNXParameters);
addParameter(p, 'InputDataPermutation', 'auto');
addParameter(p, 'OutputDataPermutation', 'auto');
addParameter(p, 'Training', false);
parse(p, input, params, varargin{:});
inputDataPerms = p.Results.InputDataPermutation;
outputDataPerms = p.Results.OutputDataPermutation;
Training = p.Results.Training;
if isnumeric(inputDataPerms)
    inputDataPerms = {inputDataPerms};
end
if isstring(inputDataPerms) && isscalar(inputDataPerms) || ischar(inputDataPerms)
    inputDataPerms = repmat({inputDataPerms},1,1);
end
if isnumeric(outputDataPerms)
    outputDataPerms = {outputDataPerms};
end
if isstring(outputDataPerms) && isscalar(outputDataPerms) || ischar(outputDataPerms)
    outputDataPerms = repmat({outputDataPerms},1,numDataOutputs);
end
end

function [input, Training, outputDataPerms, anyDlarrayInputs] = preprocessInput(input, params, varargin)
% Parse input arguments
[inputDataPerms, outputDataPerms, Training] = parseInputs(input, 1, params, varargin{:});
anyDlarrayInputs = any(cellfun(@(x)isa(x, 'dlarray'), {input}));
% Make the input variables into unlabelled dlarrays:
input = makeUnlabeledDlarray(input);
% Permute inputs if requested:
input = permuteInputVar(input, inputDataPerms{1}, 4);
% Check input size(s):
checkInputSize(size(input), {'batch' 3 512 768}, "input");
end

function [output] = postprocessOutput(output, outputDataPerms, anyDlarrayInputs, Training, varargin)
% Set output type:
if ~anyDlarrayInputs && ~Training
    if isdlarray(output)
        output = extractdata(output);
    end
end
% Permute outputs if requested:
output = permuteOutputVar(output, outputDataPerms{1}, 4);
end


%% dlarray functions implementing ONNX operators:

function [Y, numDimsY] = onnxConcat(ONNXAxis, XCell, numDimsXArray)
% Concatentation that treats all empties the same. Necessary because
% dlarray.cat does not allow, for example, cat(1, 1x1, 1x0) because the
% second dimension sizes do not match.

% Copyright 2021 The MathWorks, Inc.

numDimsY = numDimsXArray(1);
XCell(cellfun(@isempty, XCell)) = [];
if isempty(XCell)
    Y = dlarray([]);
else
    if ONNXAxis<0
        ONNXAxis = ONNXAxis + numDimsY;
    end
    DLTAxis = numDimsY - ONNXAxis;
    Y = cat(DLTAxis, XCell{:});
end
end

function [weights, bias, stride, dilationFactor, padding, dataFormat, numDimsY] = prepareConvArgs(...
    weights, bias, stride, dilationFactor, padding, numWtGroups, numDimsX, numDimsW)
% Prepares arguments for implementing the ONNX Conv operator

%   Copyright 2020 The MathWorks, Inc.

% Weights: The ONNX weight dim is Fcxyz..., where c=C/G, G is numGroups,
% and xyz... are spatial dimensions. DLT "weights" here is the flip of
% that, or ...zyxcF. dlconv requires ...zyxcfG, where f=F/G. So reshape to
% split the last dimension.
sizeW    = size(weights, 1:numDimsW);
F        = sizeW(end);
newWSize = [sizeW(1:numDimsW-1), F/numWtGroups, numWtGroups];
weights  = reshape(weights, newWSize);
% bias
if isempty(bias)
    bias = 0;
end
bias = dlarray(bias(:),'CU');
% Derive missing default attributes from weight tensor
numSpatialDims = numDimsW-2;
if isempty(padding)
    padding = zeros(1, 2*numSpatialDims);
end
if isempty(stride)
    stride = ones(1,numSpatialDims);
end
if isempty(dilationFactor)
    dilationFactor = ones(1,numSpatialDims);
end
% Make the attributes non-dlarrays:
if isa(stride, 'dlarray')
    stride = extractdata(stride);
end
if isa(dilationFactor, 'dlarray')
    dilationFactor = extractdata(dilationFactor);
end
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
% Make the attributes double row vectors, and flip their dimension ordering
% to reverse-onnx:
stride = fliplr(double(stride(:)'));
dilationFactor = fliplr(double(dilationFactor(:)'));
if isnumeric(padding)       % padding can be "same"
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
% Set dataformat and numdims
dataFormat = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY = numDimsX;
end

function [weights, bias, stride, dilation, cropping, dataFormat, numDimsY] = prepareConvTransposeArgs(ONNXWeights, bias, stride, dilation, pads, auto_pad, output_shape, numWtGroups, sizeX, numDimsX, numDimsW)
% Prepares arguments for implementing the ONNX ConvTranspose operator

%   Copyright 2020-2021 The MathWorks, Inc.

% The ONNX weight dim is Cfhwd..., where f=F/G, G is numGroups and hwd...
% are the spatial dimensions of the kernel. The input argumnt "ONNXWeights"
% here is the flip of that, or ...dwhfC. We want ...dwhfcG, where c=C/G. So
% we just need to perform a reshape to split the last dimension from C to
% cG.
sizeW       = size(ONNXWeights, 1:numDimsW);
C           = sizeW(end);
newWSize    = [sizeW(1:numDimsW-1), C/numWtGroups, numWtGroups];
weights     = reshape(ONNXWeights, newWSize);
if isempty(bias)
    bias = 0;
end
bias = dlarray(bias(:),'CU');
% Derive missing default attributes from weight tensor
numSpatialDims = numDimsW-2;
if isempty(pads)
    pads = zeros(1, 2*numSpatialDims);
end
if isempty(stride)
    stride = ones(1,numSpatialDims);
end
if isempty(dilation)
    dilation = ones(1,numSpatialDims);
end
% Make the attributes non-dlarrays:
if isa(stride, 'dlarray')
    stride = extractdata(stride);
end
if isa(dilation, 'dlarray')
    dilation = extractdata(dilation);
end
if isa(pads, 'dlarray')
    pads = extractdata(pads);
end
if isa(output_shape, 'dlarray')
    output_shape = extractdata(output_shape);
end
if ~isempty(output_shape)
    % Process output_shape. The ONNX Doc says:
    % "If output_shape is specified pads values are ignored."
    % And then 'pads' is recalculated as follows:
    % total_padding[i] = stride[i] * (input_size[i] - 1) + output_padding[i] + ((kernel_shape[i] - 1) * dilations[i] + 1) - output_shape[i]
    % If (auto_pads == SAME_UPPER): pads[start_i] = total_padding[i]/2; pads[end_i] = total_padding[i] - (total_padding[i]/2)
    % Else: pads[start_i] = total_padding[i] - (total_padding[i]/2); pads[end_i] = (total_padding[i]/2).

    % sizeX is reverse-onnx with trailing singletons dropped. ...zyxCN.
    % Extract the ONNX spatial shape as 'input_size', and put it in forward
    % ONNX ordering.
    if numDimsX > numel(sizeX)
        sizeX = [sizeX, ones(1,numDimsX-numel(sizeX))];     % sizeX is now ...zyxCN
    end
    input_size = fliplr(sizeX(1:numSpatialDims));     % xyz...
    % Recover the kernel_shape from the weights in forward ONNX ordering
    kernel_shape = fliplr(sizeW(1:numSpatialDims));
    % Calculate the new pads value in forward ONNX ordering
    output_padding = 0;             % output_padding is not supported (yet).
    D = numel(input_size);
    for i = 1:D
        total_padding(i) = stride(i) * (input_size(i) - 1) + output_padding + ((kernel_shape(i) - 1) * dilation(i) + 1) - output_shape(i);
        start_i = i;
        end_i = D+i;
        if auto_pad=="SAME_UPPER"
            pads(start_i) = floor(total_padding(i)/2);
            pads(end_i) = total_padding(i) - floor(total_padding(i)/2);
        else
            pads(start_i) = total_padding(i) - floor(total_padding(i)/2);
            pads(end_i) = floor(total_padding(i)/2);
        end
    end
end
% Make the attributes double row vectors, and flip their dimension ordering
% to reverse-onnx:
stride = fliplr(double(stride(:)'));
dilation = fliplr(double(dilation(:)'));
if isnumeric(pads)       % padding can be "same"
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the left-right flip and the semicolon)
    pads = fliplr(transpose(reshape(pads, [], 2)));
end
cropping = pads;
dataFormat  = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY = numDimsX;
end

function [poolsize, stride, padding, dataFormat, numDimsY, numDimsIndices] = prepareMaxPool8Args(poolsize, stride, padding, numDimsX)
% Prepares arguments for implementing the ONNX MaxPool-8 operator

%   Copyright 2020 The MathWorks, Inc.

poolsize    = fliplr(extractdata(poolsize(:)'));
stride      = fliplr(extractdata(stride(:)'));
% padding
if isa(padding, 'dlarray')
    padding = extractdata(padding);
end
if isnumeric(padding)
    % ONNX: [x1_begin, ..., xn_begin, x1_end, ...,xn_end]
    % DLT:  [xn_begin, ..., x1_begin;
    %        xn_end, ..., x1_end]       (Note the lrflip and semicolon)
    padding = fliplr(transpose(reshape(padding, [], 2)));
end
dataFormat  = [repmat('S', 1, numDimsX-2) 'CB'];
numDimsY    = numDimsX;
numDimsIndices = numDimsX;                      % New in opset 8
end

%% Utility functions:

function s = appendStructs(varargin)
% s = appendStructs(s1, s2,...). Assign all fields in s1, s2,... into s.

%   Copyright 2020 The MathWorks, Inc.

if isempty(varargin)
    s = struct;
else
    s = varargin{1};
    for i = 2:numel(varargin)
        fromstr = varargin{i};
        fs = fieldnames(fromstr);
        for j = 1:numel(fs)
            s.(fs{j}) = fromstr.(fs{j});
        end
    end
end
end

function checkInputSize(inputShape, expectedShape, inputName)

%   Copyright 2020-2021 The MathWorks, Inc.

if numel(expectedShape)==0
    % The input is a scalar
    if ~isequal(inputShape, [1 1])
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, "[1,1]", inputSizeStr));
    end
elseif numel(expectedShape)==1
    % The input is a vector
    if ~shapeIsColumnVector(inputShape) || ~iSizesMatch({inputShape(1)}, expectedShape)
        expectedShape{2} = 1;
        expectedSizeStr = makeSizeString(expectedShape);
        inputSizeStr = makeSizeString(inputShape);
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
else
    % The input has 2 dimensions or more

    % The input dimensions have been reversed; flip them back to compare to the
    % expected ONNX shape.
    inputShape = fliplr(inputShape);

    % If the expected shape has fewer dims than the input shape, error.
    if numel(expectedShape) < numel(inputShape)
        expectedSizeStr = strjoin(["[", strjoin(string(expectedShape), ","), "]"], "");
        error(message('nnet_cnn_onnx:onnx:InputHasGreaterNDims', inputName, expectedSizeStr));
    end

    % Prepad the input shape with trailing ones up to the number of elements in
    % expectedShape
    inputShape = num2cell([ones(1, numel(expectedShape) - length(inputShape)) inputShape]);

    % Find the number of variable size dimensions in the expected shape
    numVariableInputs = sum(cellfun(@(x) isa(x, 'char') || isa(x, 'string'), expectedShape));

    % Find the number of input dimensions that are not in the expected shape
    % and cannot be represented by a variable dimension
    nonMatchingInputDims = setdiff(string(inputShape), string(expectedShape));
    numNonMatchingInputDims  = numel(nonMatchingInputDims) - numVariableInputs;

    expectedSizeStr = makeSizeString(expectedShape);
    inputSizeStr = makeSizeString(inputShape);
    if numNonMatchingInputDims == 0 && ~iSizesMatch(inputShape, expectedShape)
        % The actual and expected input dimensions match, but in
        % a different order. The input needs to be permuted.
        error(message('nnet_cnn_onnx:onnx:InputNeedsPermute',inputName, expectedSizeStr, inputSizeStr));
    elseif numNonMatchingInputDims > 0
        % The actual and expected input sizes do not match.
        error(message('nnet_cnn_onnx:onnx:InputNeedsResize',inputName, expectedSizeStr, inputSizeStr));
    end
end
end

function doesMatch = iSizesMatch(inputShape, expectedShape)
% Check whether the input and expected shapes match, in order.
% Size elements match if (1) the elements are equal, or (2) the expected
% size element is a variable (represented by a character vector or string)
doesMatch = true;
for i=1:numel(inputShape)
    if ~(isequal(inputShape{i},expectedShape{i}) || ischar(expectedShape{i}) || isstring(expectedShape{i}))
        doesMatch = false;
        return
    end
end
end

function sizeStr = makeSizeString(shape)
sizeStr = strjoin(["[", strjoin(string(shape), ","), "]"], "");
end

function isVec = shapeIsColumnVector(shape)
if numel(shape) == 2 && shape(2) == 1
    isVec = true;
else
    isVec = false;
end
end
function X = makeUnlabeledDlarray(X)
% Make numeric X into an unlabelled dlarray

%   Copyright 2020-2021 The MathWorks, Inc.

if isa(X, 'dlarray')
    X = stripdims(X);
elseif isnumeric(X)
    if isinteger(X)
        % Make ints double so they can combine with anything without
        % reducing precision
        X = double(X);
    end
    X = dlarray(X);
end
end

function [Vars, NumDims] = packageVariables(params, inputNames, inputValues, inputNumDims)

%   Copyright 2020 The MathWorks, Inc.

% inputNames, inputValues are cell arrays. inputRanks is a numeric vector.
Vars = appendStructs(params.Learnables, params.Nonlearnables, params.State);
NumDims = params.NumDimensions;
% Add graph inputs
for i = 1:numel(inputNames)
    Vars.(inputNames{i}) = inputValues{i};
    NumDims.(inputNames{i}) = inputNumDims(i);
end
end

function X = permuteInputVar(X, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
% Returns reverse-ONNX ordering
if onnxNDims == 0
    return;
elseif onnxNDims == 1 && isvector(X)
    X = X(:);
    return;
elseif isnumeric(userDataPerm)
    % Permute into reverse ONNX ordering
    if numel(userDataPerm) ~= onnxNDims
        error(message('nnet_cnn_onnx:onnx:InputPermutationSize', numel(userDataPerm), onnxNDims));
    end
    perm = fliplr(userDataPerm);
elseif isequal(userDataPerm, 'auto') && onnxNDims == 4
    % Permute MATLAB HWCN to reverse onnx (WHCN)
    perm = [2 1 3 4];
elseif isequal(userDataPerm, 'as-is')
    % Do not permute the input
    perm = 1:ndims(X);
else
    % userDataPerm is either 'none' or 'auto' with no default, which means
    % it's already in onnx ordering, so just make it reverse onnx
    perm = max(2,onnxNDims):-1:1;
end
X = permute(X, perm);
end

function Y = permuteOutputVar(Y, userDataPerm, onnxNDims)

%   Copyright 2020-2021 The MathWorks, Inc.
switch onnxNDims
    case 0
        perm = [];
    case 1
        if isnumeric(userDataPerm)
            % Use the user's permutation because Y is a column vector which
            % already matches ONNX.
            perm = userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            % Treat the 1D onnx vector as a 2D column and transpose it
            perm = [2 1];
        else
            % userDataPerm is 'none'. Leave Y alone because it already
            % matches onnx.
            perm = [];
        end
    otherwise
        % ndims >= 2
        if isnumeric(userDataPerm)
            % Use the inverse of the user's permutation. This is not just the
            % flip of the permutation vector.
            perm = onnxNDims + 1 - userDataPerm;
        elseif isequal(userDataPerm, 'auto')
            if onnxNDims == 2
                % Permute reverse ONNX CN to DLT CN (do nothing)
                perm = [];
            elseif onnxNDims == 4
                % Permute reverse onnx (WHCN) to MATLAB HWCN
                perm = [2 1 3 4];
            else
                % User wants the output in ONNX ordering, so just reverse it from
                % reverse onnx
                perm = onnxNDims:-1:1;
            end
        elseif isequal(userDataPerm, 'as-is')
            % Do not permute the input
            perm = 1:ndims(Y);
        else
            % userDataPerm is 'none', so just make it reverse onnx
            perm = onnxNDims:-1:1;
        end
end
if ~isempty(perm)
    Y = permute(Y, perm);
end
end

function s = updateStruct(s, t)
% Set all existing fields in s from fields in t, ignoring extra fields in
% t.
%   Copyright 2020 The MathWorks, Inc.

for name = transpose(fieldnames(s))
    s.(name{1}) = t.(name{1});
end
end
